spring:
    application:
        name: onos-mcp-server
        
    main:
        web-application-type: none
        banner-mode: off

    ai:
        mcp:
            server:
                name: onos-mcp-server
                version: 0.0.1

logging:
    level:
        root: WARN
        "[org.springframework.cloud.openfeign]": DEBUG

onos:
    controller:
        host: ${ONOS_CONTROLLER_HOST:http://localhost:8181}
        username: ${ONOS_CONTROLLER_USERNAME:onos}
        password: ${ONOS_CONTROLLER_PASSWORD:rocks}
        